services:
  nginx:
    container_name: ${CONTAINER_NAME}-NGINX
    image: nginx:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:rw
      - wordpress:/var/www/html
    networks:
      - internal

  database:
    container_name: ${CONTAINER_NAME}-MYSQL
    image: mysql:latest
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$DATABASE_ROOT_PASSWORD" ]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

  phpmyadmin:
    container_name: ${CONTAINER_NAME}-PHPMYADMIN
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
    ports:
      - "8081:80"
    networks:
      - internal

  wordpress:
    depends_on: 
      - database
    container_name: ${CONTAINER_NAME}-WORDPRESS
    image: wordpress:6.8.1-fpm-alpine
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${DATABASE_NAME}'
      WORDPRESS_DB_USER: '${DATABASE_USER}'
      WORDPRESS_DB_PASSWORD: '${DATABASE_PASSWORD}'
    volumes:
      - wordpress:/var/www/html
    networks:
      - internal
    
# end of services

volumes:  
  dbdata:
  wordpress:

networks:
  internal:
    driver: bridge